string1 = input('Digite alguma coisa: ')
string2 = input('Digite outra coisa: ')
print(f'A quantidade total de caracteres digitado foi {len(string1) + len(string2)}')
print(f'Aqui está a String1 em minúsculo: {string1.lower()}')
print(f'Aqui está a String2 em maiúsculo: {string2.upper()}')
